server:
  port: 8282
spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/datajpa

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql : true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace